name = "JuliaStudies"
uuid = "268e46ef-aeb3-459e-bb72-ba8574d61cfe"
authors = ["Haotian Li <htsli@ucdavis.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
